### ISSUE TITLE
[KK-DESIGN] 홈 화면 디자인

### ISSUE THREAD

**Issue by se-ryeong** [nbcamp-archive/kkuk-ios#18]
## Description

- 화면의 구성요소를 생성합니다.

## Tasks

- [x] 오늘의 추천 문구 추가
- [x] pageControl + scrollView
- [x] floating 버튼

**Comment by yujinkim1** [comment]
@se-ryeong 가능하면 작성한 작업 개수와 commit & push횟수를 1:1 형태로 맞춰주세요!
