### ISSUE TITLE
[KK-DESIGN] 검색 화면 디자인

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#19]
## Description

- 검색 화면에 Component 를 추가합니다.
- Component의 오토레이아웃을 설정합니다.

### 검색 메인 컨트롤러 표시 사항
- [x] SearchBar : 검색창 추가
- [x] TableView : 아카이브 컨텐츠 
- [x] Cell : 아카이브 컨텐츠 cell
- [x] Label : 아카이브 없을 때 표시

### 검색창 탭했을 때 표시 사항
- [x] ViewController : 검색창 선택 시, 최근 검색어  표시
- [x] TableView : 최근 검색어 10개 표시
- [x] Cell : 최근 검색어 cell
- [x] Label : 최근 검색어 없을 경우 표시
- [x] Button :  최근 검색어 전체 삭제 버튼 
- [x] Button : 뒤로가기 버튼 

## ETC

- 기능 연결은 하지 않습니다.

**Comment by yujinkim1** [comment]
@jooYeonStudyiOS 가능하면 작성한 작업 개수와 commit & push횟수를 1:1 형태로 맞춰주세요!
