### ISSUE TITLE
[KK-DESIGN] 카테고리 생성화면 디자인 

### ISSUE THREAD

**Issue by Sonyeongha** [nbcamp-archive/kkuk-ios#20]
## Description

- 카테고리 생성하는 페이지 제작 

## Tasks

- [ ] 입력창
- [ ] 아이콘

**Comment by yujinkim1** [comment]
@Sonyeongha 가능하면 작성한 작업 개수와 commit & push횟수를 1:1 형태로 맞춰주세요!
